name: DNA Evolve Thanks
favicon: null
layout_spectrum: 0.5872007869184017
typography_spectrum: 0.24594892328605056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4807011093944311
  lightness: 0.04597041290253401
  saturation: 0.781542380573228
  rhythmicContrast: 0.17734023346565664
purpose: []
