name: DNA Evolve Thanks
favicon: null
layout_spectrum: 0.25042
typography_spectrum: 0.24594892328605056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#423aa5'
    - '#7989e9'
    - '#040208'
    - '#5a5e7e'
    - '#e3e9fe'
  brandStrength: 0
  lightness: 0.04597041290253401
  saturation: 0.5
  rhythmicContrast: 0.17734023346565664
purpose: []
